### ISSUE TITLE
Classification_AppRoles.json Additions

### ISSUE THREAD

**Issue by dwarfered** [Cloud-Architekt/AzurePrivilegedIAM#8]
Hi @Cloud-Architekt , I would do a PR for these. but not sure my assumptions are correct.

TermStore.Read.All (Microsoft SharePoint) ManagementPlane? 
Tasks.ReadWrite.All (Microsoft 365 Platform Management) ManagementPlan?
UserAuthenticationMethod.Read.All (Authentication) ManagementPlane?

**Comment by Cloud-Architekt** [comment]
I've added the API permissions to the latest classification update. I've tagged all of them as Management Plane, exclude UserAuthenticationMethod.Read.All. Those does not included sensitive information and should be covered by the default member permissions as well. Feel free to share your thoughts on this if you do not agree. :)

**Comment by dwarfered** [comment]
Thanks Thomas, hmm I'll check what read allows. I guess it would allow the viewing of mobile numbers where registered etc, so there's a PII aspect to it.
