### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by dtewinkel** [Cloud-Architekt/AzurePrivilegedIAM#9]
Hi Cloud-Architect,

Can you please add a license to this repository, so I know if and how I can use it. Please see [Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository): 

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

If your intention is to have no license at all (also no copyright), then I suggest to use [Unlicense](https://choosealicense.com/licenses/unlicense/).

**Comment by Cloud-Architekt** [comment]
Hi @dtewinkel , I've added a license to the repo. Thanks for the feedback. Feel free to contact me if you have any questions regarding this project. I would be also interested to see any forks or uses of the original content in other projects. :) It would be great to have it included in the [list of community projects](https://github.com/Cloud-Architekt/AzurePrivilegedIAM?tab=readme-ov-file#-community-use-cases-and-references) which are using the content.
